version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal-website-frontend-${ENVIRONMENT}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.youcandoit-frontend-${ENVIRONMENT}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.youcandoit-frontend-${ENVIRONMENT}.entrypoints=websecure"
      - "traefik.http.routers.youcandoit-frontend-${ENVIRONMENT}.tls=true"
      - "traefik.http.routers.youcandoit-frontend-${ENVIRONMENT}.tls.certresolver=cloudflare"
      - "traefik.http.routers.youcandoit-frontend-${ENVIRONMENT}.middlewares=auth-admin@docker"
    env_file:
      - .env
    networks:
      - web

networks:
  web:
    external: true 