name: Deploy to Staging and Production Servers

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  stage-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy to Staging Server
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.DEPLOY_SSH_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER_IP }} << 'EOF'
            cd /home/wach/personal-website/STAGE
            eval $(ssh-agent -s)
            ssh-add ~/.ssh/github
            git pull origin main
            docker-compose -p personal-website-stage up --build -d
          EOF

  prod-deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy to Production Server
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.DEPLOY_SSH_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER_IP }} << 'EOF'
            cd /home/wach/personal-website/PROD
            eval $(ssh-agent -s)
            ssh-add ~/.ssh/github            
            git pull origin ${{ github.ref }} 
            docker-compose -p personal-website-prod up --build -d
          EOF